// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mjbjvDFGxSrTpTIKfDLDOXq6rvtmyq4',
    appId: '1:973675940884:web:3b8ef5ac8f9d48cbe2eb01',
    messagingSenderId: '973675940884',
    projectId: 'tomadoc-7bfc8',
    authDomain: 'tomadoc-7bfc8.firebaseapp.com',
    storageBucket: 'tomadoc-7bfc8.firebasestorage.app',
    measurementId: 'G-6FZXZ63QV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8m8rhN_08KsW_a58s-_h0hvEVbZIrTnI',
    appId: '1:973675940884:android:046e5327b448de48e2eb01',
    messagingSenderId: '973675940884',
    projectId: 'tomadoc-7bfc8',
    storageBucket: 'tomadoc-7bfc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjD_UfXASflP0gR341KIgrjkjCzhyKotM',
    appId: '1:973675940884:ios:39b23e2c102a3601e2eb01',
    messagingSenderId: '973675940884',
    projectId: 'tomadoc-7bfc8',
    storageBucket: 'tomadoc-7bfc8.firebasestorage.app',
    iosBundleId: 'com.example.tomadoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjD_UfXASflP0gR341KIgrjkjCzhyKotM',
    appId: '1:973675940884:ios:39b23e2c102a3601e2eb01',
    messagingSenderId: '973675940884',
    projectId: 'tomadoc-7bfc8',
    storageBucket: 'tomadoc-7bfc8.firebasestorage.app',
    iosBundleId: 'com.example.tomadoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0mjbjvDFGxSrTpTIKfDLDOXq6rvtmyq4',
    appId: '1:973675940884:web:f16396eee82024b9e2eb01',
    messagingSenderId: '973675940884',
    projectId: 'tomadoc-7bfc8',
    authDomain: 'tomadoc-7bfc8.firebaseapp.com',
    storageBucket: 'tomadoc-7bfc8.firebasestorage.app',
    measurementId: 'G-LJ2WB8M3HB',
  );
}
